name: DevSecOps Security Scan

on:
  push:
    branches:
      - main

jobs:
  security-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Checkov Scan
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform
          soft_fail: true

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          scanners: vuln,secret